# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'
use_frameworks!

def AccessAppExercise_pods
    
end
target 'AccessAppExercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'Alamofire'
    pod 'SDWebImage', '~> 5.0'
    pod 'PKHUD', '~> 5.0'
end

